services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - DATABASE_URL={DATABASE_URL}
        - JWT_SECRET={JWT_SECRET}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  promethus:
    container_name: promethus
    image: prom/prometheus:v2.55.0
    volumes:
      - ./Docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - go-networks

  graphana:
    container_name: graphana
    image: grafana/grafana:9.5.2
    ports:
      - 3000:3000
    networks:
      - go-networks
    volumes:
      - ./Docker/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-data:/var/lib/grafana
